Estetika/Models/Entities/Polzovatel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estetika.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzovatel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polzovatel()
        {
            this.Otvet = new HashSet<Otvet>();
            this.Otziv = new HashSet<Otziv>();
            this.Tovar = new HashSet<Tovar>();
            this.Zapis = new HashSet<Zapis>();
        }
    
        public int ID_Polzovatel { get; set; }
        public string Imya { get; set; }
        public string Phamilia { get; set; }
        public string Electronnya_Pochta { get; set; }
        public Nullable<long> Telephon { get; set; }
        public string Login { get; set; }
        public string Parol { get; set; }
        public int ID_Tip_Polzovatel { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otvet> Otvet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otziv> Otziv { get; set; }
        public virtual Tip_Polzovatel Tip_Polzovatel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tovar> Tovar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapis> Zapis { get; set; }
    }
}

Estetika/Controllers/PolzovatelsController.cs
using Estetika.Models.Entities;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
namespace Estetika.Controllers
{
    public class PolzovatelsController : Controller
    {
        private readonly SalonEntities db = new SalonEntities();

        // GET: Polzovatels
        public ActionResult Index()
        {
            var polzovatel = db.Polzovatel
                .Include(p => p.Tip_Polzovatel)
                .Where(u => !u.IsDeleted);
            return View(polzovatel.ToList());
        }


        // GET: Polzovatels/Details/5
        [Authorize]
        public ActionResult Details(string login)
        {
            if (login == null)
            {
                return View(
                    db.Polzovatel.First(u => u.Login == HttpContext.User.Identity.Name));
            }
            return View(
                db.Polzovatel.First(u => u.Login == login));
        }

        // GET: Polzovatels/Create
        public ActionResult Create()
        {
            ViewBag.ID_Tip_Polzovatel = new SelectList(db.Tip_Polzovatel, "ID_Tip_Polzovatel", "Imya_Tip_Polzovatel");
            return View();
        }

        // POST: Polzovatels/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Polzovatel,Imya,Phamilia,Electronnya_Pochta,Telephon,Login,Parol,ID_Tip_Polzovatel")] Polzovatel polzovatel)
        {
            if (ModelState.IsValid)
            {
                db.Polzovatel.Add(polzovatel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_Tip_Polzovatel = new SelectList(db.Tip_Polzovatel, "ID_Tip_Polzovatel", "Imya_Tip_Polzovatel", polzovatel.ID_Tip_Polzovatel);
            return View(polzovatel);
        }

        // GET: Polzovatels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Polzovatel polzovatel = db.Polzovatel.Find(id);
            if (polzovatel == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Tip_Polzovatel = new SelectList(db.Tip_Polzovatel, "ID_Tip_Polzovatel", "Imya_Tip_Polzovatel", polzovatel.ID_Tip_Polzovatel);
            return View(polzovatel);
        }

        // POST: Polzovatels/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Polzovatel,Imya,Phamilia,Electronnya_Pochta,Telephon,Login,Parol,ID_Tip_Polzovatel")] Polzovatel polzovatel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(polzovatel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Tip_Polzovatel = new SelectList(db.Tip_Polzovatel, "ID_Tip_Polzovatel", "Imya_Tip_Polzovatel", polzovatel.ID_Tip_Polzovatel);
            return View(polzovatel);
        }

        // GET: Polzovatels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Polzovatel polzovatel = db.Polzovatel.Find(id);
            if (polzovatel == null)
            {
                return HttpNotFound();
            }
            return View(polzovatel);
        }

        // POST: Polzovatels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Polzovatel user = db.Polzovatel.Find(id);
            user.IsDeleted = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult CancelRequest(int requestId)
        {
            using (SalonEntities entities = new SalonEntities())
            {
                Zapis request = entities.Zapis.Find(requestId);
                request.Activien = false;
                entities.SaveChanges();
                return RedirectToAction("Details", new { id = request.ID_Polzovatel });
            }
        }
    }
}

Estetika/Views/Polzovatels/Create.cshtml
@using Estetika.Models.Entities; @model Polzovatel

@{
    ViewBag.Title = "Добавить пользователя | BETAHAIR";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Добавить пользователя</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">Имя</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Imya, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Imya, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Фамилия</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phamilia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phamilia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Электронная почта </label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Electronnya_Pochta, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Electronnya_Pochta, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Телефон</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telephon, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telephon, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Логин</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Пароль</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Parol, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Parol, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Тип пользователя</label>
        <div class="col-md-10">
            @Html.DropDownList("ID_Tip_Polzovatel", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ID_Tip_Polzovatel, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Estetika/Views/Polzovatels/Delete.cshtml
@using Estetika.Models.Entities; @model Polzovatel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Вы точно хотите удалить этого пользователя?</h3>
<div>

    <hr />
   

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Удалить" class="btn btn-default" /> |

 

    @Html.ActionLink("Вернуться", "Index", "", htmlAttributes: (new { @class = "btn btn-default" }))
</div>
    }
</div>

Estetika/Views/Polzovatels/Details.cshtml
@using Estetika.Models.Entities; @model Polzovatel

@{
    ViewBag.Title = "Личный кабинет";
}

<br />
<br />
<br />
<h3 style="margin-left:50px;">Мои записи</h3>
<hr />
<div style="display:flex; flex-wrap: wrap;">
    @foreach (var item in Model.Zapis)
    {
        <div style="grid-template-rows: 70% 30%; margin: 2em; padding-left:125px;">
            <div style="position:relative;">
                @{ if (item.Activien == true)
                    {
                        <img id='previewImage' class="imgactive" style='width: 150px; height: 150px; border-radius: 100px' src="~/Resource/activ.png" />
                    }
                    else
                    {
                        <img id='previewImage' class="imgactive" style='width: 150px; height: 150px; border-radius: 100px' src="~/Resource/otmen.png" />
                    }
                }
            </div>
            <div class="rndclss" style=" width: 150px;  text-align:center;">
                <div style="margin-top:10px;">
                    @Html.ActionLink(item.Master.Tip_Master.Imya_Tip_Master, "Details", new { id = item.Master.Tip_Master.ID_Tip_Master }, new { @class = "textstyle masterstyle" })
                </div>
                <br />
                <div>
                    @Html.ActionLink(@"Мастер: " + item.Master.Imya_Master, "Details", new { id = item.ID_Master }, new { @class = "textstyle" })
                </div>
                <div>
                    @Html.ActionLink(@"Дата: " + item.Data, "Details", new { id = item.ID_Master }, new { @class = "textstyle" })
                </div>
                <div>
                    @Html.ActionLink(@"Время:" + item.Vremya, "Details", new { id = item.ID_Master }, new { @class = "textstyle" })
                </div>
                <br />
                @if (item.Activien.HasValue && item.Activien.Value)
                {
                    <div>
                        @Html.ActionLink("Отменить запись", "CancelRequest", "Polzovatels", new { requestId = item.ID_Zapis }, new { @class = "btn btn-default btnstyleformasterpage " })
                    </div>
                }
            </div>
        </div>
    }
</div>

Estetika/Views/Polzovatels/Edit.cshtml
@using Estetika.Models.Entities; @model Polzovatel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Изменить пользователя</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Polzovatel)

        <div class="form-group">
            <label class = "control-label col-md-2">Имя</label>
    
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imya, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imya, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Фамилия</label>
       
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phamilia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phamilia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Электронная почта</label>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.Electronnya_Pochta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Electronnya_Pochta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Номер телефона</label>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Логин</label>
           
            <div class="col-md-10">
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Пароль</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.Parol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Parol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Тип пользователя</label>
       
            <div class="col-md-10">
                @Html.DropDownList("ID_Tip_Polzovatel", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Tip_Polzovatel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Estetika/Views/Polzovatels/Index.cshtml
@using Estetika.Models.Entities; @model IEnumerable<Polzovatel>

@{
    ViewBag.Title = "Index";
}
<br />
<br />
<br />
<h3>Пользователи</h3>


<table class="table  table-striped">
    <tr>
        <th class="tdbackground">
            Имя
        </th>
        <th class="tdbackground">
            ФИО пользователя
        </th>
        <th class="tdbackground"> 
            Электронная почта
        </th>
        <th class="tdbackground">
            Номер телефона
        </th>
        <th class="tdbackground">
            Логин
        </th>
        <th class="tdbackground">
           Пароль
        </th>
        <th class="tdbackground">
           Тип пользователя
        </th>
        <th class="tdbackground"></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Imya)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phamilia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Electronnya_Pochta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telephon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Login)
        </td>
        <td>
            Пароль скрыт в целях безопастности
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tip_Polzovatel.Imya_Tip_Polzovatel)
        </td>
        <td>
            @Html.ActionLink("Изменить", "Edit", new { id=item.ID_Polzovatel }) |
           
            @Html.ActionLink("Удалить", "Delete", new { id=item.ID_Polzovatel })
        </td>
    </tr>
}

</table>
<button class=" btn btn-default stylebuttonfortableadd ">

    @Html.ActionLink("Добавить пользователя", "Create", new { @class = "fontcolor " })
   

</button>