Estetika/Models/Entities/Vopros.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estetika.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vopros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vopros()
        {
            this.Variant = new HashSet<Variant>();
        }
    
        public int ID_Vopros { get; set; }
        public string Zagolovok { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Variant> Variant { get; set; }
    }
}

Estetika/Controllers/VoprosController.cs
using Estetika.Models;
using Estetika.Models.Entities;
using Estetika.Models.Exceptions;
using System;
using System.Collections.Specialized;
using System.Data.Common;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
namespace Estetika.Controllers
{
    public class VoprosController : Controller
    {
        private readonly SalonEntities db = new SalonEntities();

        // GET: Vopros
        public ActionResult Index()
        {
            return View(db.Vopros.ToList());
        }


        [HttpPost]
        public ActionResult RedirectUserDependingOnChoices()
        {
            NameValueCollection choicesForm = Request.Form;

            TrySaveChoices(choicesForm);

            string hairProblemsChoice = choicesForm["Какие проблемы у вас с волосами?"];

            if (hairProblemsChoice == null)
            {
                return RedirectToAction("Index", "Sredstva");
            }
            else
            {
                return RedirectDependingOnChoice(hairProblemsChoice);
            }
        }

        /// <summary>
        /// Tries to save the selected choices to the database or throws Exception. 
        /// The saved choices are not used on the website.
        /// </summary>
        /// <param name="choicesCollection">Collection with the selected choices.</param>
        private void TrySaveChoices(NameValueCollection choicesCollection)
        {
            try
            {
                SaveChoices(choicesCollection);
            }
            catch (DbException ex)
            {
                throw new Exception("Cannot save the choices to the db", ex);
            }
        }

        private void SaveChoices(NameValueCollection choicesCollection)
        {
            foreach (string answerKey in choicesCollection.Keys)
            {
                string choiceText = choicesCollection[answerKey];
                Variant choice = db.Variant.First(v => v.Tekst == choiceText);
                Otvet answer = new Otvet
                {
                    ID_Polzovatel = Me.Get().ID_Polzovatel,
                    ID_Variant = choice.ID_Variant
                };
                db.Otvet.Add(answer);
                db.SaveChanges();
            }
        }

        private ActionResult RedirectDependingOnChoice(string hairProblemsChoice)
        {
            if (hairProblemsChoice == "ломаются, секутся")
            {
                TempData[nameof(Tovar.ID_Tip_Tovar)] = GoodsTypeIds.Shampoo;
                return RedirectToAction("Index", "Sredstva");
            }
            else if (hairProblemsChoice == "пушатся")
            {
                TempData[nameof(Tovar.ID_Tip_Tovar)] = GoodsTypeIds.Elastic;
                return RedirectToAction("Index", "Sredstva");
            }
            else if (hairProblemsChoice == "невозможно расчесать")
            {
                TempData[nameof(Tovar.ID_Tip_Tovar)] = GoodsTypeIds.Comb;
                return RedirectToAction("Index", "Sredstva");
            }
            else
            {
                throw new ChoiceActionNotFoundException("The hairs problem needs more choices");
            }
        }

        // GET: Vopros/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vopros vopros = db.Vopros.Find(id);
            if (vopros == null)
            {
                return HttpNotFound();
            }
            return View(vopros);
        }

        // GET: Vopros/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vopros/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Vopros,Zagolovok")] Vopros vopros)
        {
            if (ModelState.IsValid)
            {
                db.Vopros.Add(vopros);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vopros);
        }

        // GET: Vopros/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vopros vopros = db.Vopros.Find(id);
            if (vopros == null)
            {
                return HttpNotFound();
            }
            return View(vopros);
        }

        // POST: Vopros/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Vopros,Zagolovok")] Vopros vopros)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vopros).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vopros);
        }

        // GET: Vopros/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vopros vopros = db.Vopros.Find(id);
            if (vopros == null)
            {
                return HttpNotFound();
            }
            return View(vopros);
        }

        // POST: Vopros/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vopros vopros = db.Vopros.Find(id);
            db.Vopros.Remove(vopros);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Estetika/Views/Vopros/Create.cshtml
@using Estetika.Models.Entities; @model Vopros

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vopros</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Zagolovok, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zagolovok, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zagolovok, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Estetika/Views/Vopros/Delete.cshtml
@using Estetika.Models.Entities; @model Vopros

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vopros</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Zagolovok)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zagolovok)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Estetika/Views/Vopros/Details.cshtml
@using Estetika.Models.Entities; @model Vopros

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Vopros</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Zagolovok)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zagolovok)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_Vopros }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Estetika/Views/Vopros/Edit.cshtml
@using Estetika.Models.Entities; @model Vopros

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vopros</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Vopros)

        <div class="form-group">
            @Html.LabelFor(model => model.Zagolovok, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zagolovok, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zagolovok, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Estetika/Views/Vopros/Index.cshtml
@using Estetika.Models.Entities; @model IEnumerable<Vopros>

@{
    ViewBag.Title = "Index";
}
<br />
<br />

<h3>Тест для подбора средств по уходу за волосами</h3>
<br />


@using (Html.BeginForm("RedirectUserDependingOnChoices", "Vopros"))
{
    <ul style=" list-style-type: none;">
        @foreach (var item in Model)
        {
            <li style=" list-style-type: none;">@item.Zagolovok</li>
            <li style=" list-style-type: none;">
                <ol style=" list-style-type: none;">
                    @foreach (var option in item.Variant)
                    {
                        <li>@Html.RadioButton(option.Vopros.Zagolovok, option.Tekst) @option.Tekst </li>
                    }
                </ol>
            </li>
        }
    </ul>
    <input style="margin-left:40px;" type="submit" value="Отправить" class="btn btn-default" />
}