Estetika/Models/Entities/Zapis.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estetika.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapis
    {
        public int ID_Zapis { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.TimeSpan> Vremya { get; set; }
        public Nullable<int> ID_Polzovatel { get; set; }
        public Nullable<int> ID_Master { get; set; }
        public Nullable<bool> Activien { get; set; }
    
        public virtual Master Master { get; set; }
        public virtual Polzovatel Polzovatel { get; set; }
    }
}

Estetika/Controllers/ZapisAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Estetika.Models.Entities;

namespace Estetika.Controllers
{
    public class ZapisAdminController : Controller
    {
        private SalonEntities db = new SalonEntities();

        // GET: ZapisAdmin
        public ActionResult Index()
        {
            var zapis = db.Zapis.Include(z => z.Master).Include(z => z.Polzovatel);
            return View(zapis.ToList());
        }

        // GET: ZapisAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zapis zapis = db.Zapis.Find(id);
            if (zapis == null)
            {
                return HttpNotFound();
            }
            return View(zapis);
        }

        // GET: ZapisAdmin/Create
        public ActionResult Create(int id = 0)
        {

            if (id > 0)
            {
                ViewBag.ID_Master = new SelectList(db.Master, "ID_Master", "Imya_Master", db.Master.First(m => m.ID_Master == id).ID_Master);
            }
            else
            {
                ViewBag.ID_Master = new SelectList(db.Master, "ID_Master", "Imya_Master", db.Master.First().ID_Master);
            }

            ViewBag.ID_Polzovatel = new SelectList(db.Polzovatel, "ID_Polzovatel", "Imya");
            return View();
        }

        // POST: ZapisAdmin/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "ID_Zapis,Data,Vremya,ID_Polzovatel,ID_Master,Activien")] Zapis zapis)
        {
            if (ModelState.IsValid)
            {
                Zapis newRequest = new Zapis
                {
                    Data = zapis.Data.Value,
                    Vremya = zapis.Vremya.Value,
                    ID_Polzovatel = db.Polzovatel.First(u => u.Login == HttpContext.User.Identity.Name).ID_Polzovatel,
                    ID_Master = zapis.ID_Master,
                    Activien = true
                };
                db.Zapis.Add(newRequest);
                db.SaveChanges();
                return RedirectToAction("Index", "Zapis");
            }

            ViewBag.ID_Master = new SelectList(db.Master, "ID_Master", "Imya_Master", zapis.ID_Master);
            ViewBag.ID_Polzovatel = new SelectList(db.Polzovatel, "ID_Polzovatel", "Imya", zapis.ID_Polzovatel);
            return View(zapis);
        }

        // GET: ZapisAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zapis zapis = db.Zapis.Find(id);
            if (zapis == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Master = new SelectList(db.Master, "ID_Master", "Imya_Master", zapis.ID_Master);
            ViewBag.ID_Polzovatel = new SelectList(db.Polzovatel, "ID_Polzovatel", "Imya", zapis.ID_Polzovatel);
            return View(zapis);
        }

        // POST: ZapisAdmin/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Zapis,Data,Vremya,ID_Polzovatel,ID_Master,Activien")] Zapis zapis)
        {
            if (ModelState.IsValid)
            {
                db.Entry(zapis).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Master = new SelectList(db.Master, "ID_Master", "Imya_Master", zapis.ID_Master);
            ViewBag.ID_Polzovatel = new SelectList(db.Polzovatel, "ID_Polzovatel", "Imya", zapis.ID_Polzovatel);
            return View(zapis);
        }

        // GET: ZapisAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zapis zapis = db.Zapis.Find(id);
            if (zapis == null)
            {
                return HttpNotFound();
            }
            return View(zapis);
        }

        // POST: ZapisAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Zapis zapis = db.Zapis.Find(id);
            db.Zapis.Remove(zapis);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Estetika/Controllers/ZapisController.cs
using Estetika.Models.Entities;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
namespace Estetika.Controllers
{
    public class ZapisController : Controller
    {
        private readonly SalonEntities db = new SalonEntities();

        // GET: Zapis
        public ActionResult Index()
        {
            var zapis = db.Zapis.Include(z => z.Master).Include(z => z.Polzovatel);
            return View(zapis.ToList());
        }

        // GET: Zapis/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zapis zapis = db.Zapis.Find(id);
            if (zapis == null)
            {
                return HttpNotFound();
            }
            return View(zapis);
        }

        // GET: Zapis/Create
        public ActionResult Create(int id = 0)
        {
            if (id > 0)
            {
                ViewBag.ID_Master = new SelectList(db.Master, "ID_Master", "Imya_Master", db.Master.First(m => m.ID_Master == id).ID_Master);
            }
            else
            {
                ViewBag.ID_Master = new SelectList(db.Master, "ID_Master", "Imya_Master", db.Master.First().ID_Master);
            }

            ViewBag.ID_Polzovatel = new SelectList(db.Polzovatel, "ID_Polzovatel", "Imya");
            return View();
        }

        // POST: Zapis/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "ID_Zapis,Data,Vremya,ID_Polzovatel,ID_Master,Activien")] Zapis zapis)
        {
            if (ModelState.IsValid)
            {
                Zapis newRequest = new Zapis
                {
                    Data = zapis.Data.Value,
                    Vremya = zapis.Vremya.Value,
                    ID_Polzovatel = db.Polzovatel.First(u => u.Login == HttpContext.User.Identity.Name).ID_Polzovatel,
                    ID_Master = zapis.ID_Master,
                    Activien = true
                };

                db.Zapis.Add(newRequest);
                db.SaveChanges();
                return RedirectToAction("Details", "Polzovatels");
            }

            ViewBag.ID_Master = new SelectList(db.Master, "ID_Master", "Imya_Master", zapis.ID_Master);
            ViewBag.ID_Polzovatel = new SelectList(db.Polzovatel, "ID_Polzovatel", "Imya", zapis.ID_Polzovatel);
            return View(zapis);
        }

        // GET: Zapis/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zapis zapis = db.Zapis.Find(id);
            if (zapis == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Master = new SelectList(db.Master, "ID_Master", "Imya_Master", zapis.ID_Master);
            ViewBag.ID_Polzovatel = new SelectList(db.Polzovatel, "ID_Polzovatel", "Imya", zapis.ID_Polzovatel);
            return View(zapis);
        }

        // POST: Zapis/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Zapis,Data,Vremya,ID_Polzovatel,ID_Master,Activien")] Zapis zapis)
        {
            if (ModelState.IsValid)
            {
                db.Entry(zapis).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Master = new SelectList(db.Master, "ID_Master", "Imya_Master", zapis.ID_Master);
            ViewBag.ID_Polzovatel = new SelectList(db.Polzovatel, "ID_Polzovatel", "Imya", zapis.ID_Polzovatel);
            return View(zapis);
        }

        // GET: Zapis/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zapis zapis = db.Zapis.Find(id);
            if (zapis == null)
            {
                return HttpNotFound();
            }
            return View(zapis);
        }

        // POST: Zapis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Zapis zapis = db.Zapis.Find(id);
            db.Zapis.Remove(zapis);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult CancelRequest(int requestId)
        {
            using (SalonEntities entities = new SalonEntities())
            {
                Zapis request = entities.Zapis.Find(requestId);
                request.Activien = false;
                entities.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Estetika/Views/Zapis/Create.cshtml
@using Estetika.Models.Entities; @model Zapis

@{
    @Styles.Render("~/Content/StylePage/AddEditZaisStyle.css")
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">
        <!-- code here -->
        <div class="card">
            <div class="card-image">
            </div>
            <form class="card-form">
                <div class="input">
                    <label class="input-label">Дата записи</label>
                    @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control radiusinput", @type = "date" } })
                    @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
                </div>
                <div class="input">
                    <label class="input-label">Время записи</label>
                    @Html.ValidationMessageFor(model => model.Vremya, "", new { @class = "text-danger" })
                    <ul style=" list-style-type: none; margin-top:20px; margin-left:-25px; ">

                        <li>@Html.RadioButtonFor(request => request.Vremya, TimeSpan.FromHours(8), new { htmlAttributes = new { @class = "rdbtn" } }) 8:00  </li>
                        <li>@Html.RadioButtonFor(request => request.Vremya, TimeSpan.FromHours(10), new { htmlAttributes = new { @class = "rdbtn" } }) 10:00 </li>
                        <li>@Html.RadioButtonFor(request => request.Vremya, TimeSpan.FromHours(13), new { htmlAttributes = new { @class = "rdbtn" } }) 13:00  </li>
                        <li>@Html.RadioButtonFor(request => request.Vremya, TimeSpan.FromHours(15), new { htmlAttributes = new { @class = "rdbtn" } }) 15:00  </li>
                        <li>@Html.RadioButtonFor(request => request.Vremya, TimeSpan.FromHours(17), new { htmlAttributes = new { @class = "rdbtn" } }) 17:00  </li>
                    </ul>
                </div>
                <div class="input">
                    <label class="input-label">Мастер</label>
                    @Html.DropDownList("ID_Master", null, htmlAttributes: new { @class = "form-control radiusinput" })
                    @Html.ValidationMessageFor(model => model.ID_Master, "", new { @class = "text-danger" })
                </div>
                <div class="action">
                    <input type="submit" value="Записаться" class="btn btn-default action-button" />
                </div>
            </form>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Estetika/Views/Zapis/Delete.cshtml
@using Estetika.Models.Entities; @model Zapis

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Вы точно хотите удалить эту запись?</h3>
<div>
   
    <hr />
    

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться к заявкам", "Index", "", htmlAttributes: ( new {@class = "btn btn-default" }))
        </div>
    }
</div>

Estetika/Views/Zapis/Details.cshtml
@using Estetika.Models.Entities; @model Zapis

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Zapis</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vremya)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vremya)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Master.Imya_Master)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Master.Imya_Master)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Polzovatel.Imya)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Polzovatel.Imya)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_Zapis }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Estetika/Views/Zapis/Edit.cshtml
@using Estetika.Models.Entities; @model Zapis

@{
    ViewBag.Title = "Запись клиента | BETAHAIR";
}


<br />
<br />
<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Запись клиента</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Zapis)

        <div class="form-group">
            <label class="control-label col-md-2">Дата</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Время</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vremya, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vremya, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Клиент</label>
            <div class="col-md-10">
                @Html.DropDownList("ID_Polzovatel", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Polzovatel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Мастер</label>
            <div class="col-md-10">
                @Html.DropDownList("ID_Master", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Master, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Активность заявки</label>
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activien)
                    @Html.ValidationMessageFor(model => model.Activien, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к записям", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Estetika/Views/Zapis/Index.cshtml
@using Estetika.Models.Entities; @model IEnumerable<Zapis>

@{
    ViewBag.Title = "Учет записи клиентов";
}
<br />
<br />
<h3>Учет записи клиентов</h3>



<table class="table table-striped">
    <tr>
        <th class="tdbackground">
            Клиент
        </th>
        <th class="tdbackground">
            Телефон
        </th>
        <th class="tdbackground">
            Cпециалист
        </th>
        <th class="tdbackground">
            Дата
        </th>
        <th class="tdbackground">
            Время
        </th>
        <th class="tdbackground">
            Активность заявки
        </th>
        <th class="tdbackground">
            Отмена записи
        </th>


        <th class="tdbackground"></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Polzovatel.Imya) @Html.DisplayFor(modelItem => item.Polzovatel.Phamilia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Polzovatel.Telephon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Master.Imya_Master)
            </td>
            <td>
                @(item.Data)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vremya)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Activien)
            </td>
            <td>
                @Html.ActionLink(
               "Отменить",
               "CancelRequest",
               nameof(Zapis),
               routeValues: new { requestId = item.ID_Zapis },
               htmlAttributes: new { @class = "btn btn-default stylebuttonfortable" })
            </td>



            <td>
                @Html.ActionLink("Изменить", "Edit", new { id = item.ID_Zapis }) |

                @Html.ActionLink("Удалить", "Delete", new { id = item.ID_Zapis })
            </td>
        </tr>
    }

</table>
<button class=" btn btn-default stylebuttonfortableadd ">

    @Html.ActionLink("Добавить", "Create", "ZapisAdmin")

</button>