Estetika/Models/Entities/Otziv.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estetika.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otziv
    {
        public int ID_Otziv { get; set; }
        public string Napisanny_Otziv { get; set; }
        public Nullable<int> ID_Polzovatel { get; set; }
    
        public virtual Polzovatel Polzovatel { get; set; }
    }
}

Estetika/Controllers/OtzivsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Estetika;

using Estetika.Models.Entities; namespace Estetika.Controllers
{
    public class OtzivsController : Controller
    {
        private readonly SalonEntities db = new SalonEntities();

        // GET: Otzivs
        public ActionResult Index()
        {
            var otziv = db.Otziv.Include(o => o.Polzovatel);
            return View(otziv.ToList());
        }

        // GET: Otzivs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Otziv otziv = db.Otziv.Find(id);
            if (otziv == null)
            {
                return HttpNotFound();
            }
            return View(otziv);
        }

        // GET: Otzivs/Create
        public ActionResult Create()
        {
            ViewBag.ID_Polzovatel = new SelectList(db.Polzovatel, "ID_Polzovatel", "Imya");
            return View();
        }

        // POST: Otzivs/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Otziv,Otziv1,ID_Polzovatel")] Otziv otziv)
        {
            if (ModelState.IsValid)
            {
                db.Otziv.Add(otziv);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_Polzovatel = new SelectList(db.Polzovatel, "ID_Polzovatel", "Imya", otziv.ID_Polzovatel);
            return View(otziv);
        }

        // GET: Otzivs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Otziv otziv = db.Otziv.Find(id);
            if (otziv == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Polzovatel = new SelectList(db.Polzovatel, "ID_Polzovatel", "Imya", otziv.ID_Polzovatel);
            return View(otziv);
        }

        // POST: Otzivs/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Otziv,Otziv1,ID_Polzovatel")] Otziv otziv)
        {
            if (ModelState.IsValid)
            {
                db.Entry(otziv).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Polzovatel = new SelectList(db.Polzovatel, "ID_Polzovatel", "Imya", otziv.ID_Polzovatel);
            return View(otziv);
        }

        // GET: Otzivs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Otziv otziv = db.Otziv.Find(id);
            if (otziv == null)
            {
                return HttpNotFound();
            }
            return View(otziv);
        }

        // POST: Otzivs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Otziv otziv = db.Otziv.Find(id);
            db.Otziv.Remove(otziv);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        public ActionResult PostComment(string comment)
        {
            if ( comment == null || comment == "")
            {
                ModelState.AddModelError(nameof(comment), "Введите комментарий");
            }
            if (ModelState.IsValid)
            {

                Otziv newComment = new Otziv
            {
              Napisanny_Otziv = comment,
               ID_Polzovatel = db.Polzovatel.First(u => u.Login == HttpContext.User.Identity.Name).ID_Polzovatel
              
           };
           db.Otziv.Add(newComment);
           db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Estetika/Views/Otzivs/Create.cshtml
@using Estetika.Models.Entities; @model Otziv

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Otziv</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Otziv1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Otziv1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Otziv1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Polzovatel, "ID_Polzovatel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Polzovatel", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Polzovatel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Estetika/Views/Otzivs/Delete.cshtml
@using Estetika.Models.Entities; @model Otziv

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Otziv</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Otziv1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Otziv1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Polzovatel.Imya)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Polzovatel.Imya)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Estetika/Views/Otzivs/Details.cshtml
@using Estetika.Models.Entities; @model Otziv

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Otziv</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Otziv1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Otziv1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Polzovatel.Imya)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Polzovatel.Imya)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_Otziv }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Estetika/Views/Otzivs/Edit.cshtml
@using Estetika.Models.Entities; @model Otziv

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Otziv</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Otziv)

        <div class="form-group">
            @Html.LabelFor(model => model.Otziv1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Otziv1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Otziv1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Polzovatel, "ID_Polzovatel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Polzovatel", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Polzovatel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Estetika/Views/Otzivs/Index.cshtml
@using Estetika.Models.Entities; @model IEnumerable<Otziv>

@{
    ViewBag.Title = "Index";
}
<br />
<br />
<br />
<div>
    <h3 style="margin-left:15px; ">Отзывы</h3>

</div>




<section class="container">
    <div class="row">

        <div class="col-md-12">
            <div class="panel">
                <div class="panel-body">
                    @using (Html.BeginForm("PostComment", "Otzivs", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        
                        <textarea name="comment" class="form-control" rows="2" style="height:80px;" placeholder="Добавьте Ваш комментарий"></textarea>
                        //Валидацию об ошибке
                        <div class="mar-top clearfix">
                            <button class="btn btn-sm btn-primary pull-left" type="submit"><i class="fa fa-pencil fa-fw"></i> Добавить</button>
                        </div>


                    }
                    <br />
                    <br />
                    <br />
                </div>
                </div>
                <div class="panel">
                    <div class="panel-body">
                        @foreach (var item in Model)
                        {
                            <div class="media-block">
                                <a class="media-left" href="#"><img class="img-circle img-sm" alt="Профиль пользователя" src="~/Resource/userphoto.png"></a>

                                <div class="media-body">
                                    <div class="mar-btm">
                                        <a href="#" class="btn-link text-semibold media-heading box-inline"> @(item.Polzovatel.Imya)</a>
                                    </div>
                                    <p>@(item.Napisanny_Otziv)</p>
                                    <hr>
                                </div>
                            </div>

                        }
                    </div>
                </div>
            </div>
        </div><!-- /.row -->
    </section><!-- /.container -->